id: I8DAACEB7
legacy_id: P000533
ocr_import_info:
  bdrc_scan_id: W00KG03797
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T06:45:57'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:11:36.862682+00:00'
last_modified: 2022-08-29 20:11:47.705839
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG03797
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00KG03797
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐུབ་བསྟན་རྡོ་རྗེ་བྲག་དགོན་གྱི་བྱུང་བ་མདོ་ཙམ་བརྗོད་པ་ངོ་མཚར་བཻ་ཌཱུ་རྱའི་ཕྲེང་བ།
  author: ཡོན་དོ་མཆོག་སྤྲུལ་ཀུན་བཟང་འགྲོ་འདུལ་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.9357910326029526
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I00KG03832:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03832
      total_pages: 49
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG03832.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9357910326029526
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
